name: AudioNote
options:
  bundleIdPrefix: info.karsa.app
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    ENABLE_USER_SCRIPT_SANDBOXING: NO

targets:
  AudioNote:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: AudioNote
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: AudioNote/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: info.karsa.app.ios.audionote
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
    info:
      path: AudioNote/Resources/Info.plist
      properties:
        CFBundleName: AudioNote
        CFBundleDisplayName: AudioNote
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundlePackageType: APPL
        LSRequiresIPhoneOS: true
        UILaunchScreen:
          UIColorName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}
        NSMicrophoneUsageDescription: "AudioNote 需要访问麦克风以进行语音录制和识别。"
        NSSpeechRecognitionUsageDescription: "AudioNote 需要使用语音识别功能将您的语音转换为文字。"
        NSAppleMusicUsageDescription: ""
        NSMotionUsageDescription: ""

  AudioNoteTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: AudioNoteTests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: info.karsa.app.ios.audionote.tests
    dependencies:
      - target: AudioNote

  AudioNoteUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: AudioNoteUITests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: info.karsa.app.ios.audionote.uitests
    dependencies:
      - target: AudioNote
